Repository DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO2, pull requests merged in 2024-10, with the labels that each got.

#4 [chore] 기본 파일 구조 세팅 완료
  DomadoV/DomadoV/App/ContentView.swift
  DomadoV/DomadoV/App/DomadoVApp.swift
  DomadoV/DomadoV/Coordinator/AppCoordinator .swift
  DomadoV/DomadoV/Model/LocationData.swift
  DomadoV/DomadoV/Model/RestPeriod.swift
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/Model/RideSummary.swift
  DomadoV/DomadoV/Model/SpeedDistribution.swift
  DomadoV/DomadoV/Persistent/CoreDataManager.swift
  DomadoV/DomadoV/Service/LocationManager.swift
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/View/PauseRideView.swift
  DomadoV/DomadoV/View/RidePreparationView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
  DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🧹chore

#6 [feat] 뷰 계층 구조 관리 AppCoordinator 구현
  DomadoV/DomadoV/App/ContentView.swift
  DomadoV/DomadoV/Coordinator/AppCoordinator .swift
  DomadoV/DomadoV/Coordinator/AppView.swift
  DomadoV/DomadoV/Coordinator/RideEvent.swift
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/View/PauseRideView.swift
  DomadoV/DomadoV/View/RidePreparationView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
  DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
  DomadoV/DomadoV/ViewModel/RideEventPublishable.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#8 [feat] 데이터 모델링
  DomadoV/DomadoV/Model/LocationData.swift
  DomadoV/DomadoV/Model/RestPeriod.swift
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/Model/RideSummary.swift
  DomadoV/DomadoV/Model/SpeedDistribution.swift
Labels: 🐣feature

#11 [feat] 화면 이동 로직 구현
  DomadoV/DomadoV/App/ContentView.swift
  DomadoV/DomadoV/Coordinator/AppCoordinator .swift
  DomadoV/DomadoV/Coordinator/AppView.swift
  DomadoV/DomadoV/Coordinator/RideEvent.swift
  DomadoV/DomadoV/View/RideDetailView.swift
  DomadoV/DomadoV/View/RideHistoryCell.swift
  DomadoV/DomadoV/View/RideHistoryView.swift
  DomadoV/DomadoV/View/RidePreparationView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#21 [feat] 커스텀 폰트 적용
  DomadoV/DomadoV.xcodeproj/project.pbxproj
  DomadoV/DomadoV/Fonts/Pretendard-ExtraLight.otf
  DomadoV/DomadoV/Fonts/Pretendard-Regular.otf
  DomadoV/DomadoV/Fonts/RobotoCondensed-Black.ttf
  DomadoV/DomadoV/Fonts/RobotoCondensed-Bold.ttf
  DomadoV/DomadoV/Fonts/RobotoCondensed-Regular.ttf
  DomadoV/DomadoV/Fonts/RobotoCondensed-SemiBold.ttf
  DomadoV/DomadoV/Info.plist
  DomadoV/DomadoV/Utill/CustomFont.swift
  DomadoV/DomadoV/Utill/FontView.swift
Labels: 🐣feature

#22 [feat] LocationManager 구현
  DomadoV/DomadoV.xcodeproj/project.pbxproj
  DomadoV/DomadoV/Service/LocationManager.swift
Labels: 🔨enhancement

#24 [feat] LocationManager 권한 발행자 및 RideSession 메서드 추가
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/Service/LocationManager.swift
Labels: 🐣feature

#26 [feat] RideSession 관리 Flow 구현
  DomadoV/DomadoV/App/ContentView.swift
  DomadoV/DomadoV/Coordinator/AppCoordinator .swift
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/View/PauseRideView.swift
  DomadoV/DomadoV/View/RidePreparationView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
  DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#28 [feat] 주행 준비화면 동작 구현
  DomadoV/DomadoV.xcodeproj/project.pbxproj
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/RidePreparationView.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
Labels: 🐣feature

#30 [feat] 주행중 화면 업데이트 및 동작 로직 구현
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
  DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
Labels: 🐣feature

#36 [enh] 정지시 속도 반영 개선
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/Service/LocationManager.swift
Labels: 🔨enhancement

#47 [chore] 앱 이름 및 아이콘 추가
  DomadoV/DomadoV.xcodeproj/project.pbxproj
  DomadoV/DomadoV/Assets.xcassets/AccentColor.colorset/Contents.json
  DomadoV/DomadoV/Assets.xcassets/AppIcon.appiconset/Contents.json
  DomadoV/DomadoV/Assets.xcassets/AppIcon.appiconset/pacepalcon 1.png
  DomadoV/DomadoV/Assets.xcassets/AppIcon.appiconset/pacepalcon 2.png
  DomadoV/DomadoV/Assets.xcassets/AppIcon.appiconset/pacepalcon.png
Labels: 🧹chore

#48 [feat] CoreDataManager 구현
  DomadoV/DomadoV/Persistent/CoreDataManager.swift
Labels: 🐣feature

#49 [feat] 주행 요약 기능 구현
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#33 [feat] 주행기록 화면 구현
  DomadoV/DomadoV/View/RideHistoryCell.swift
  DomadoV/DomadoV/View/RideHistoryView.swift
Labels: 🐣feature

#32 feat/#13-주행정지(휴식)화면 구현
  DomadoV/DomadoV/View/PauseRideView.swift
Labels: 🐣feature

#50 [feat] 엔티티 구조 설계
  DomadoV/DomadoV/Persistent/PacepalModel.xcdatamodeld/PacepalModel.xcdatamodel/contents
  DomadoV/DomadoV/Persistent/Ride+CoreDataClass.swift
  DomadoV/DomadoV/Persistent/Ride+CoreDataProperties.swift
  DomadoV/DomadoV/Utill/LocationCompressionUtility.swift
Labels: 🐣feature

#51 [feat] RideHistoryManager 구현
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/Service/RideHistoryManager.swift
Labels: 🐣feature

#52 [feat] 주행 종료시 주행 정보 저장
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#37 [feat] 주행기록 상세 화면 구현
  DomadoV/DomadoV/View/RideDetailView.swift
Labels: 🐣feature

#53 [feat] RideHistoryViewModel 주행기록 fetch 로직 추가
  DomadoV/DomadoV/Model/RideRecord.swift
  DomadoV/DomadoV/Service/RideHistoryManager.swift
  DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift
Labels: 🐣feature

#55 [fix] 롱프레스를 통한 주행 정지
  DomadoV/DomadoV/View/PauseRideView.swift
Labels: 🐛bug

#58 [bug] 경로 데이터 없을시 저장 실패
  DomadoV/DomadoV/Persistent/PacepalModel.xcdatamodeld/PacepalModel.xcdatamodel/contents
Labels: 🐛bug

#61 [feat] 지도상 주행 경로를 표시합니다.
  DomadoV/DomadoV/View/Component/RideRouteMapView.swift
Labels: 🐣feature

#63 [feat] 실제 저장된 주행기록 보여주기
  DomadoV/DomadoV/Extension/Extension+Date.swift
  DomadoV/DomadoV/Extension/Extension+Double.swift
  DomadoV/DomadoV/Extension/Extension+TimeInterval.swift
  DomadoV/DomadoV/Model/RideRecord.swift
  DomadoV/DomadoV/Model/SpeedDistribution.swift
  DomadoV/DomadoV/Service/RideHistoryManager.swift
  DomadoV/DomadoV/View/Component/RideRouteMapView.swift
  DomadoV/DomadoV/View/Component/SpeedDistributionView.swift
  DomadoV/DomadoV/View/RideDetailView.swift
  DomadoV/DomadoV/View/RideHistoryCell.swift
  DomadoV/DomadoV/View/RideHistoryView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
  DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift
  DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
Labels: 🐣feature

#65 [feat] 휴식 화면 실제 정보 표시
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/PauseRideView.swift
  DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
Labels: 🐣feature

#67 [feat] 주행시작전 카운트 다운
  DomadoV/DomadoV/App/ContentView.swift
  DomadoV/DomadoV/Coordinator/AppCoordinator .swift
  DomadoV/DomadoV/Coordinator/AppView.swift
  DomadoV/DomadoV/Coordinator/RideEvent.swift
  DomadoV/DomadoV/Model/RideSession.swift
  DomadoV/DomadoV/View/CountdownView.swift
  DomadoV/DomadoV/ViewModel/CountdonwViewModel.swift
  DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
Labels: 🐣feature

#69 [feat] 주행 화면 구현
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
Labels: 🐣feature

#71 [feat] 휴식 화면 버튼 수정
  DomadoV/DomadoV/View/PauseRideView.swift
Labels: 🐣feature

#68 [feat] 주행완료 화면 구현
  DomadoV/DomadoV/Extension/Extension+TimeInterval.swift
  DomadoV/DomadoV/View/Component/SpeedDistributionView.swift
  DomadoV/DomadoV/View/RideSummaryView.swift
Labels: 🐣feature

#73 [feat] 호모양 범위 슬라이더 구현
  DomadoV/DomadoV/View/Component/ArcRangeSlider.swift
Labels: 🐣feature

#78 [feat] 주행 화면 배경 색상 변경 적용
  DomadoV/DomadoV/View/ActiveRideView.swift
  DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
Labels: 🐣feature
